name: Tests (Main)
on:
  push:
    branches:
      - main
      - v3
jobs:
  test:
    name: "Test Main Branch"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install
      - name: Lint Code
        run: pnpm lint
      - name: Run Unit Tests
        run: pnpm test
      - name: Upload Coverage Reports to Codecov
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v6
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Build Documentation
        run: pnpm build:docs
      - name: Build Library
        run: pnpm build
